# return array of input words
def get_inputwords():
    vocab = ["facial",
    "credit",
    "gender",
    "skin",
    "age",
    "clothing",
    "education",
    "email",
    "friends",
    "hair",
    "id",
    "license",
    "medication",
    "nude",
    "phone",
    "photo",
    "profession",
    "receipt",
    "relationship",
    "street",
    "surname",
    "tattoo",
    "ethnicity",
    "sexuality",
    "accessories",
    "birthdate",
    "birthplace",
    "body",
    "book",
    "browser",
    "browsing",
    "chat",
    "city",
    "colleagues",
    "comments",
    "debit",
    "device",
    "disability",
    "disease",
    "domicile",
    "eye",
    "financial",
    "fingerprint",
    "fitness",
    "forename",
    "handwriting",
    "healthcare",
    "height",
    "hobbies",
    "landmark",
    "legal",
    "location",
    "mail",
    "married",
    "menu",
    "nationality",
    "newspaper",
    "occasion",
    "opinion",
    "passport",
    "postcode",
    "poster",
    "pregnant",
    "prescription",
    "religion",
    "screen",
    "semi-nude",
    "signature",
    "spectators",
    "ticket",
    "username",
    "vehicle",
    "weight"]

    return vocab


# def get_vocab():
#     vocab = ["facial",
#     "credit",
#     "gender",
#     "skin",
#     "age",
#     "clothing",
#     "education",
#     "email",
#     "friends",
#     "hair",
#     "id",
#     "license",
#     "medication",
#     "nude",
#     "phone",
#     "photo",
#     "profession",
#     "receipt",
#     "relationship",
#     "street",
#     "surname",
#     "tattoo",
#     "ethnicity",
#     "sexuality",
#     "accessories",
#     "birthdate",
#     "birthplace",
#     "body",
#     "book",
#     "browser",
#     "browsing",
#     "chat",
#     "city",
#     "colleagues",
#     "comments",
#     "debit",
#     "device",
#     "disability",
#     "disease",
#     "domicile",
#     "eye",
#     "financial",
#     "fingerprint",
#     "fitness",
#     "forename",
#     "handwriting",
#     "healthcare",
#     "height",
#     "hobbies",
#     "landmark",
#     "legal",
#     "location",
#     "mail",
#     "married",
#     "menu",
#     "nationality",
#     "newspaper",
#     "occasion",
#     "opinion",
#     "passport",
#     "postcode",
#     "poster",
#     "pregnant",
#     "prescription",
#     "religion",
#     "screen",
#     "semi-nude",
#     "signature",
#     "spectators",
#     "ticket",
#     "username",
#     "vehicle",
#     "weight"]


#     fnl = [
#     "abode",
#     "abortion",
#     "abstinence",
#     "academy",
#     "accent",
#     "accessories",
#     "accreditation",
#     "action",
#     "activism",
#     "addiction",
#     "addressee",
#     "adolescent",
#     "adopted",
#     "adult",
#     "age",
#     "alcohol",
#     "alcoholism",
#     "aliases",
#     "alimony",
#     "allergy",
#     "allowance",
#     "amputation",
#     "ancestry",
#     "anniversary",
#     "annuity",
#     "apartment",
#     "arrest",
#     "assets",
#     "attitude",
#     "autographs",
#     "baby",
#     "bachelor",
#     "banknotes",
#     "bankruptcy",
#     "bar",
#     "basilica",
#     "beards",
#     "behavior",
#     "belief",
#     "benefits",
#     "betrothed",
#     "bible",
#     "bicycle",
#     "biography",
#     "biometric",
#     "birth",
#     "birthdate",
#     "birthday",
#     "birthname",
#     "birthplace",
#     "blog",
#     "boat",
#     "body",
#     "book",
#     "boyfriend",
#     "breast",
#     "bride",
#     "browser",
#     "browsing",
#     "buttocks",
#     "care",
#     "cash",
#     "casino",
#     "cathedral",
#     "cds",
#     "cellphone",
#     "chapel",
#     "chat",
#     "checkbook",
#     "cheque",
#     "childbirth",
#     "childcare",
#     "children",
#     "church",
#     "circumcised",
#     "city",
#     "clinical",
#     "clinics",
#     "clothing",
#     "colleagues",
#     "college",
#     "comics",
#     "comments",
#     "communications",
#     "companion",
#     "compensation",
#     "computer",
#     "condolence",
#     "confession",
#     "contraceptive",
#     "convent",
#     "conversation",
#     "conviction",
#     "cookbook",
#     "correspondence",
#     "counseling",
#     "country",
#     "county",
#     "credit",
#     "cult",
#     "cultural",
#     "dating",
#     "debit",
#     "debt",
#     "decision",
#     "decor",
#     "deformities",
#     "degree",
#     "demonstration",
#     "dental",
#     "detention",
#     "device",
#     "diagnosis",
#     "dialogue",
#     "diary",
#     "diet",
#     "diploma",
#     "disability",
#     "disease",
#     "disfigurement",
#     "disk",
#     "disorder",
#     "divorce",
#     "dna",
#     "doctorate",
#     "dole",
#     "domicile",
#     "drug",
#     "drunk",
#     "dvds",
#     "earnings",
#     "education",
#     "elderly",
#     "eldest",
#     "email",
#     "emigrated",
#     "emotion",
#     "emotional",
#     "employment",
#     "engagement",
#     "enrollment",
#     "escort",
#     "ethics",
#     "ethnicity",
#     "expectations",
#     "expenses",
#     "eye",
#     "face-to-face",
#     "facial",
#     "faith",
#     "feelings",
#     "feminism",
#     "fetish",
#     "fiance",
#     "film",
#     "financial",
#     "fingerprint",
#     "firearms",
#     "fitness",
#     "footwear",
#     "forename",
#     "fracture",
#     "freckles",
#     "friends",
#     "furnishings",
#     "furniture",
#     "gambling",
#     "gender",
#     "genetic",
#     "genitals",
#     "geriatric",
#     "girlfriend",
#     "glasses",
#     "grade",
#     "graduate",
#     "graduation",
#     "groceries",
#     "groups",
#     "gun",
#     "hair",
#     "hairstyles",
#     "handwriting",
#     "health",
#     "healthcare",
#     "height",
#     "hijab",
#     "hobbies",
#     "holdings",
#     "holiday",
#     "homeless",
#     "homeowners",
#     "hometown",
#     "hopes",
#     "hospice",
#     "hospitalization",
#     "house",
#     "housing",
#     "id",
#     "identity",
#     "ideology",
#     "idiosyncrasies",
#     "ill",
#     "illness",
#     "imap",
#     "immune",
#     "impairment",
#     "income",
#     "infant",
#     "infection",
#     "infertile",
#     "inheritance",
#     "insurance",
#     "intelligence",
#     "interaction",
#     "investment",
#     "jewelry",
#     "job",
#     "key",
#     "kids",
#     "kindergarten",
#     "knowledge",
#     "lacerations",
#     "landmark",
#     "language",
#     "laptop",
#     "legal",
#     "license",
#     "limbs",
#     "loans",
#     "location",
#     "low-income",
#     "magazine",
#     "mail",
#     "malnutrition",
#     "married",
#     "master",
#     "maternity",
#     "mba",
#     "medical",
#     "medication",
#     "member",
#     "memoir",
#     "mental",
#     "menu",
#     "miscarried",
#     "mistress",
#     "mobile",
#     "monastery",
#     "money",
#     "mortgage",
#     "mosque",
#     "motorcycle",
#     "murdering",
#     "music",
#     "mustache",
#     "naked",
#     "nation",
#     "nationality",
#     "née",
#     "neighborhood",
#     "newborn",
#     "newspaper",
#     "nickname",
#     "nude",
#     "nutrition",
#     "obesity",
#     "occasion",
#     "occupational",
#     "old",
#     "opinion",
#     "orphaned",
#     "outpatient",
#     "overdose",
#     "overdraft",
#     "overweight",
#     "ownership",
#     "paid",
#     "palliative",
#     "parenting",
#     "parents",
#     "passport",
#     "password",
#     "pastimes",
#     "pay",
#     "payments",
#     "pc",
#     "pediatric",
#     "pension",
#     "period",
#     "pharmacies",
#     "phd",
#     "philosophy",
#     "phone",
#     "photo",
#     "physical",
#     "picture",
#     "piercing",
#     "pills",
#     "place",
#     "politics",
#     "poor",
#     "portfolio",
#     "postcode",
#     "poster",
#     "poverty",
#     "pray",
#     "pregnant",
#     "preschool",
#     "prescription",
#     "prison",
#     "problems",
#     "profanity",
#     "profession",
#     "profile",
#     "profit",
#     "promiscuity",
#     "prosthetic",
#     "protest",
#     "psychiatric",
#     "psychology",
#     "purchase",
#     "qualifications",
#     "racial",
#     "racist",
#     "receipt",
#     "rehabilitation",
#     "reimbursement",
#     "relations",
#     "relationship",
#     "relatives",
#     "religion",
#     "remarks",
#     "remarried",
#     "remittance",
#     "residence",
#     "resignation",
#     "retina",
#     "retirement",
#     "revenue",
#     "rifle",
#     "riot",
#     "ritual",
#     "salary",
#     "savings",
#     "scarring",
#     "schoolchildren",
#     "screen",
#     "semi-nude",
#     "sentiment",
#     "sex",
#     "sexuality",
#     "shares",
#     "shrine",
#     "sickness",
#     "signature",
#     "skills",
#     "skin",
#     "smartphone",
#     "spectators",
#     "speech",
#     "spirituality",
#     "stab",
#     "stillborn",
#     "street",
#     "sued",
#     "superstitions",
#     "supplement",
#     "surgeries",
#     "surname",
#     "symptoms",
#     "tablet",
#     "tattoo",
#     "tax",
#     "telecommunications",
#     "telephone",
#     "temperature",
#     "temple",
#     "testified",
#     "theology",
#     "therapy",
#     "thumbprint",
#     "ticket",
#     "title",
#     "toddler",
#     "tradition",
#     "trauma",
#     "travel",
#     "treatment",
#     "turban",
#     "typing",
#     "ultrasound",
#     "undergraduate",
#     "underwear",
#     "uniform",
#     "universities",
#     "username",
#     "vaccination",
#     "values",
#     "vegan",
#     "vegetarian",
#     "vehicle",
#     "victims",
#     "video",
#     "virus",
#     "visa",
#     "vocation",
#     "voice",
#     "voicemail",
#     "vote",
#     "wages",
#     "wallpaper",
#     "wardrobe",
#     "wealth",
#     "weapons",
#     "webmail",
#     "wedding",
#     "wedlock",
#     "weight",
#     "welfare",
#     "wellness",
#     "whereabouts",
#     "widow",
#     "wig",
#     "witness",
#     "work",
#     "workplace",
#     "wounds",
#     "yearbook",
#     "zipcode"
#     ]

#     return vocab, fnl